### ISSUE TITLE
TypeError: 'SVC' object is not callable

### ISSUE THREAD

**Issue by ellery0912** [visionbike/Digital-Bio-Signal-Analysis#1]
Hi, I've trained my single channel model with the latest version but i still got the same Error as before.
here's the error messsge:
///////////////////////////////////////////////////////////////////
Receiving signal...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:/Users/user/Downloads/Digital-Bio-Signal-Analysis-master/control.py", line 141, in serial_read
    y_preds = self.cls(feature)
TypeError: 'SVC' object is not callable"
///////////////////////////////////////////////////////////////////
Is there any solution? Thanks

**Comment by visionbike** [comment]
Hi @ellery0912,

It should be self.cls.predict(feature). Please edit it in your code
Thanks
